language: php

php:
    - 5.4
    - 5.5
    - 5.6
    #- hhvm
    - nightly
    - "7.0"



sudo: false



git:
    submodules: false



addons:
    apt:
        packages:
            #- php-codesniffer
            #- phpmd
            #- shellcheck



matrix:
    allow_failures:
        - php: nightly



before_script:
    - composer update



script:
    - composer validate
    - phpunit



notifications:
    irc: "irc.freenode.org#dbwebb"
